import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import bg from "../public/bg.jpg"
// import "../../i18n"
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

import { dir } from 'i18next'
import { Navbar } from "../components/nav/client";
import Footer from "../components/footer";


const languages = ['en', 'ar']

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }))
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface props {
  children: React.ReactNode;
  params: {
    lang: string;
  };
}
export default function RootLayout({
  children,
  params: { lang },
}:
props
  
) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <body 
      >
        
        <div className="relative bg-bg z-10 h-full ">

<div className="absolute w-full h-full top-0 left-0 bg-black opacity-80 -z-10  ">

</div>
        
                <Navbar lang={lang}></Navbar>

        {children}

        <Footer></Footer>
        </div>

      </body>
    </html>
  );
}
